version: '3.5'

services:

  app: 
    # image: node:16
    container_name: phones-awesome
    build: .
    command: yarn install
    volumes: 
      - ./:/app
      - ./app/node_modules
    working_dir: /app
    ports: 
      - 8080:8080
    stdin_open: true
    tty: true
    command: npm run start